DROP TABLE IF EXISTS Users;

CREATE TABLE IF NOT EXISTS Users (
ID VARCHAR(20) PRIMARY KEY,
PASSWORD VARCHAR(20),
NAME VARCHAR(50),
ROLE VARCHAR(20)
);

INSERT INTO USERS VALUES('test','test123','관리자','Admin');
INSERT INTO USERS VALUES('user1','user1','홍길동','User');

DROP TABLE IF EXISTS Board;
CREATE TABLE IF NOT EXISTS Board (
    SEQ INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(200),
    WRITER VARCHAR(20),
    CONTENT VARCHAR(2000),
    REGDATE DATE DEFAULT NOW(),
    CNT INT DEFAULT 0
);

INSERT INTO BOARD (SEQ, TITLE, WRITER, CONTENT)
VALUES (1,'가입인사','관리자','잘 부탁드립니다...');

select * from board;
select * from users;